#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version = "2"

[formatters]
enable = ["goimports", "gofumpt"]

[formatters.settings.gofumpt]
module-path = "github.com/asciimoo/hister"

[formatters.settings.goimports]
local-prefixes = ["github.com/asciimoo"]
